/*
 * Runs both benchmark harnesses and writes bench/RESULTS.md.
 *
 * Measures three things:
 *   throughput  parse an expression and take ten occurrences, as distributions
 *   cold start  process launch to first answer, which is where a compiled
 *               binary and a script runtime differ most
 *   memory      what each runtime holds after the same workload
 *
 * Usage:  npm run bench
 */
'use strict';

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const COLD_RUNS = 30;
// The first launch of each program pays for reading it off disk, which says
// nothing about the program. One discarded run per side removes it.
const COLD_DISCARD = 1;

function run(cmd, args, opts = {}) {
  return execFileSync(cmd, args, {
    cwd: root,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    shell: process.platform === 'win32',
    ...opts,
  });
}

const batches = process.argv.includes('--quick') ? '40' : '200';
const warmup = process.argv.includes('--quick') ? '50' : '200';

console.log(`measuring the port (${batches} batches per pattern)`);
const port = JSON.parse(run('go', ['run', './bench', `-batches=${batches}`, `-warmup=${warmup}`]));

console.log(`measuring the original (${batches} batches per pattern)`);
const original = JSON.parse(
  run('node', ['bench/original.js', `--batches=${batches}`, `--warmup=${warmup}`]),
);

/**
 * Cold start: the whole process, from launch to first answer.
 *
 * The port is built to a binary first so the measurement is the program
 * starting rather than the Go toolchain compiling it, which would be a
 * comparison of build systems.
 */
console.log(`measuring cold start (${COLD_RUNS} runs each)`);
const binaryName = process.platform === 'win32' ? 'bench-port.exe' : 'bench-port';
const binary = path.join(root, binaryName);
run('go', ['build', '-o', binaryName, './bench']);

function timeProcess(cmd, args, opts = {}) {
  const samples = [];
  for (let i = 0; i < COLD_RUNS + COLD_DISCARD; i++) {
    const t0 = process.hrtime.bigint();
    run(cmd, args, opts);
    if (i >= COLD_DISCARD) samples.push(Number(process.hrtime.bigint() - t0) / 1e6);
  }
  samples.sort((a, b) => a - b);
  return {
    p50: samples[Math.floor(0.5 * (samples.length - 1))],
    p99: samples[Math.floor(0.99 * (samples.length - 1))],
    min: samples[0],
    max: samples[samples.length - 1],
  };
}

// The binary is launched without a shell, so its absolute path needs no
// quoting even on a checkout whose directory contains a space, and a Windows
// shell's refusal to search the working directory does not apply.
const coldPort = timeProcess(binary, ['-mode=coldstart'], { shell: false });
const coldOriginal = timeProcess('node', ['bench/original.js', '--mode=coldstart']);
fs.rmSync(binary, { force: true });

// --- report ----------------------------------------------------------------

const us = (ns) => (ns / 1000).toFixed(1);
const ratio = (a, b) => (b > 0 ? (a / b).toFixed(2) : 'n/a');
const mb = (bytes) => (bytes / 1024 / 1024).toFixed(1);

const byPattern = new Map(original.measurements.map((m) => [m.pattern, m]));

let faster = 0;
let slower = 0;
const rows = port.measurements.map((p) => {
  const o = byPattern.get(p.pattern);
  if (p.p50Ns < o.p50Ns) faster++;
  else slower++;
  return (
    `| \`${p.pattern}\` | ${us(o.p50Ns)} | ${us(p.p50Ns)} | **${ratio(o.p50Ns, p.p50Ns)}x** | ` +
    `${us(o.p99Ns)} | ${us(p.p99Ns)} | ${ratio(o.p99Ns, p.p99Ns)}x |`
  );
});

const totalOriginal = original.measurements.reduce((a, m) => a + m.p50Ns, 0);
const totalPort = port.measurements.reduce((a, m) => a + m.p50Ns, 0);

const doc = `# Benchmark results

Generated by \`npm run bench\` on ${new Date().toISOString()}.

| | |
|---|---|
| Original | ${original.runtime} |
| Port | ${port.runtime} |
| Workload | ${port.workload} |
| Patterns | the 15 in the original's own \`benchmarks/benchmark-inputs.ts\` |

## Methodology

The corpus is the original library's own benchmark input, not a set chosen here.
Using the author's patterns removes the temptation to pick expressions that
flatter the port, and it includes the cases that are slow for both: hashed
fields, last-weekday forms, and nth-weekday forms.

**Both sides are measured identically.** Each sample is the mean cost of one
operation across a batch, where the batch size is calibrated per pattern so a
batch takes at least 10 ms. Batching is not a convenience: Go's clock on this
machine advances in steps of about 527 microseconds, and one operation costs
tens of microseconds, so timing calls individually returned zero for every
sample. Node's timer is fine-grained enough to avoid that, but measuring the two
differently would make the comparison meaningless, so both batch.

Each pattern is warmed for ${port.warmup} operations before measurement, which
lets the JIT settle on one side and the zone database load on the other.
${port.batches} batches are then measured per pattern.

**What p99 means here.** It is the 99th percentile of batch means, not of
individual operations. At this granularity that is the honest reading: it
captures run-to-run variation, including garbage collection, rather than the
tail of a single call.

## Throughput

Per-operation cost in microseconds. Lower is better; the ratio is how many times
faster the port is.

| Pattern | Original p50 | Port p50 | Speedup | Original p99 | Port p99 | p99 ratio |
|---|---:|---:|---:|---:|---:|---:|
${rows.join('\n')}

**Summary.** The port is faster on ${faster} of ${port.measurements.length}
patterns${slower > 0 ? ` and slower on ${slower}` : ''}. Summing the median cost
across all patterns, the port is **${ratio(totalOriginal, totalPort)}x** faster
overall.

## Cold start

Process launch to first answer: parse \`*/15 9-17 * * 1-5\` and produce one
occurrence, then exit. ${COLD_RUNS} runs each. The port is compiled to a binary
first, so this measures the program starting rather than the Go toolchain
building it.

| | p50 | p99 | min | max |
|---|---:|---:|---:|---:|
| Original (node) | ${coldOriginal.p50.toFixed(1)} ms | ${coldOriginal.p99.toFixed(1)} ms | ${coldOriginal.min.toFixed(1)} ms | ${coldOriginal.max.toFixed(1)} ms |
| Port (binary) | ${coldPort.p50.toFixed(1)} ms | ${coldPort.p99.toFixed(1)} ms | ${coldPort.min.toFixed(1)} ms | ${coldPort.max.toFixed(1)} ms |
| **Speedup** | **${ratio(coldOriginal.p50, coldPort.p50)}x** | ${ratio(coldOriginal.p99, coldPort.p99)}x | | |

Most of the difference is the runtime itself: Node has to start V8 and load the
library before any parsing happens.

## Memory

| | After the workload | Metric |
|---|---:|---|
| Original | ${mb(original.memoryBytes)} MB | ${original.memoryMetric} |
| Port | ${mb(port.memoryBytes)} MB | ${port.memoryMetric} |

These are not the same measurement and should not be read as a clean ratio.
Node's resident set size counts the whole process including V8; Go's \`Sys\` is
the memory its runtime has obtained from the operating system, which excludes
the binary itself. Both are reported as each runtime reports them rather than
converted into a single number that would imply more precision than exists.

## Reproducing

\`\`\`bash
npm run bench          # full run, a few minutes
npm run bench -- --quick
\`\`\`

Raw output is written to \`bench/results-port.json\` and
\`bench/results-original.json\`.
`;

fs.writeFileSync(path.join(__dirname, 'RESULTS.md'), doc);
fs.writeFileSync(path.join(__dirname, 'results-port.json'), JSON.stringify(port, null, 2));
fs.writeFileSync(path.join(__dirname, 'results-original.json'), JSON.stringify(original, null, 2));
// Combined, under the name the submission anatomy asks for, carrying all four
// of the figures it lists: throughput and p99 per pattern, resident memory
// after the workload, and process startup.
fs.writeFileSync(
  path.join(__dirname, 'results.json'),
  JSON.stringify(
    {
      note: 'Generated by npm run bench. Both sides measured identically; see bench/methodology.md.',
      generatedAt: new Date().toISOString(),
      startupMs: {
        note: `Process launch to first answer, ${COLD_RUNS} runs each, first discarded. The port is compiled to a binary first so this measures the program starting rather than the Go toolchain building it.`,
        original: coldOriginal,
        port: coldPort,
        speedupP50: Number(ratio(coldOriginal.p50, coldPort.p50)),
      },
      memoryBytes: {
        note: 'Not the same measurement on both sides and not a clean ratio: Node reports resident set size for the whole process including V8, Go reports runtime Sys, which excludes the binary.',
        original: { bytes: original.memoryBytes, metric: original.memoryMetric },
        port: { bytes: port.memoryBytes, metric: port.memoryMetric },
      },
      throughput: {
        note: 'Per-operation nanoseconds, as a distribution over batch means. p99 is the 99th percentile of batch means, not of individual operations.',
        original,
        port,
      },
    },
    null,
    2,
  ),
);

console.log('');
console.log(`overall speedup (sum of medians): ${ratio(totalOriginal, totalPort)}x`);
console.log(`cold start: ${coldOriginal.p50.toFixed(1)}ms -> ${coldPort.p50.toFixed(1)}ms`);
console.log('wrote bench/RESULTS.md');
