/*
 * Embeds adapter/cron.wasm into a JavaScript module as base64.
 *
 * The adapter cannot read its own module from disk. The original's
 * CronFileParser tests replace the filesystem module wholesale, and Jest's
 * replacement covers the node: prefixed specifier as well, so any read at module
 * load time returns undefined. Embedding removes the filesystem from the load
 * path altogether.
 *
 * The output is a build artifact and is not committed.
 *
 * Usage:  node scripts/embed-wasm.js
 */
'use strict';

const fs = require('fs');
const path = require('path');

const wasmPath = path.join(__dirname, '..', 'adapter', 'cron.wasm');
const outPath = path.join(__dirname, '..', 'adapter', 'wasm-bytes.js');

if (!fs.existsSync(wasmPath)) {
  console.error(`${wasmPath} not found. Build it first: make build-wasm`);
  process.exit(2);
}

const bytes = fs.readFileSync(wasmPath);
const encoded = bytes.toString('base64');

fs.writeFileSync(
  outPath,
  `// Generated by scripts/embed-wasm.js. Do not edit, and do not commit.\n` +
    `// The port compiled to WebAssembly, embedded so the adapter never touches\n` +
    `// the filesystem at load time.\n` +
    `'use strict';\n` +
    `module.exports = '${encoded}';\n`,
);

console.log(
  `embedded ${(bytes.length / 1024 / 1024).toFixed(2)} MB as ` +
    `${(encoded.length / 1024 / 1024).toFixed(2)} MB of base64 -> ${outPath}`,
);
